pipeline:

  frontend:
    image: node:8
    commands:
	  - npm install -g vuepress
	  - vuepress build
	  - rm -rf docs
	  - mv .vuepress/dist docs

  publish:
    image: plugins/gh-release
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_password
    settings:
      pages_directory: docs/
